### ISSUE TITLE
Bounding box generation

### ISSUE THREAD

**Issue by jwdinius** [NegatioN/KaggleFisheries#1]
Your bounding box code requires json files (within the annotationHandler).  How did you generate these?  Thanks!

**Comment by NegatioN** [comment]
Hey @jwdinius :)
The bounding boxes should be available through https://www.kaggle.com/c/the-nature-conservancy-fisheries-monitoring/discussion/25902
I just extracted all of those (+ the file for the empty annotations a bit down in the thread) into my data/annotations-folder.

Edit: I believe they're hand-annotated, and as such need to be shared on Kaggle according to their rules. :)
